---
title: Partials
description: Create reusable content blocks.
position: 5
---
:relfileprefix: ../
:relfilesuffix: /

With partials, you can create reusable components so that you don't have to duplicate the same code on many pages.
Partials can use all templating engines supported by Frontman.
For more information, see <<templating-engines#content, Templating engines>>.

== Configure partial directory

By default, Frontman looks for partials in the directory `views/partials`.
To change this setting, add the following code to your `config.rb` file:

[,ruby]
----
# config.rb
Frontman::Config.set(:partials_dir, 'custom-partial-directory')
----

== Include partials in your pages

To include a partial, use the `partial` method.
It takes two parameters:

- `partial_file` (required). The path to your partial, relative to the `:partials_dir` directory.
- `data`. A hash with data to expose in the partials.

For example, you can create a partial `views/partials/test.md.erb`:

[,erb]
----
<!-- views/partials/test.md.erb -->

### Heading for <%= section %>
----

Then, in your Markdown page with the `.html.md.erb` extension,
you can include the partial:

[,erb]
----

This is text before a partial is included.

<%= partial 'test.md.erb', section: 'introduction' %>
----

== Partials with children

You can _wrap_ partials around elements on your page—similar to using React components with children.
This can be useful for creating more flexible partials, where the content can't be easily put into variables.

[,erb]
----
<!-- views/partials/test.md.erb -->

### Heading for <%= section %>

<%= yield %>
----

Then, in your Markdown page, assign the partial to a variable,
and use it like a regular ERB variable.

[,erb]
----
This is text before a partial is included.

<% partial_content = partial('test.md.erb', section: 'introduction') do %>
This text is now rendered _inside_ the partial.
<% end %>

<%= partial_content %>
----
