# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `yaml-front-matter` gem.
# Please instead update this file by running `bin/tapioca gem yaml-front-matter`.

# source://yaml-front-matter//lib/yaml/front-matter.rb#4
module Psych::FrontMatter
  class << self
    # source://yaml-front-matter//lib/yaml/front-matter.rb#8
    def extract(content); end
  end
end

# source://yaml-front-matter//lib/yaml/front-matter.rb#5
Psych::FrontMatter::PATTERN = T.let(T.unsafe(nil), Regexp)
