# "$schema": https://json-schema.org/draft/2020-12/schema
title: Frontmatter
description: Required and optional properties.
type: object
properties:
  title:
    type: string
    description: Page title.
    maxLength: 60
  description:
    type: string
    pattern: "\\.$"
    description: Page description.
    maxLength: 155
  position:
    type: integer
    description: >
      Position in the sidebar.
      If not provided, pages are added to the end in alphabetical order.
  sidebar_label:
    type: string
    description: Label for the sidebar. By default, the title is used.
additionalProperties: false
required:
  - title
  - description
