name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["3.1", "3.3"]

    env:
      BUNDLE_WITH: "docs"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Tests
        run: bundle exec rake spec

      - name: Lint
        run: bundle exec rake rubocop

      - name: Type check
        run: bundle exec rake tc

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: docs/package.json

      - name: Build docs
        run: |
          cd docs
          npm install -g pnpm
          pnpm install
          cd ..
          bundle exec rake docs
