name: Check docs

on:
  workflow_dispatch:
  push:
    paths:
      - "docs/content/**/*.html.*"
  pull_request:
    paths:
      - "docs/content/**/*.html.*"

jobs:
  docs:
    name: Check docs quality
    runs-on: ubuntu-latest

    env:
      BUNDLE_WITH: "docs"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        working-directory: ./docs
        run: |
          npm install --global pnpm
          pnpm install --frozen-lockfile

      - name: Build docs
        run: bundle exec rake docs

      - name: Check frontmatter
        run: bundle exec ruby validate_frontmatter.rb
        working-directory: ./docs

      - name: Check links
        uses: lycheeverse/lychee-action@v1.9.3
        with:
          fail: true
          args: |
            docs/build --exclude-all-private --base docs/build --exclude gstatic.com --exclude googleapis.com

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Vale
        run: pip install vale

      - name: Check styles with Vale
        run: |
          vale --output .vale/vale.tmpl content > output.log
        working-directory: ./docs

      - name: Annotate Vale issues
        run: python .vale/annotate.py output.log
        working-directory: ./docs
